# Generated by Django 3.2.8 on 2021-11-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0003_equipo_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='img',
            field=models.CharField(max_length=500, null=True, verbose_name='Imagen'),
        ),
    ]
