# Generated by Django 3.2.8 on 2021-11-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0004_equipo_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='incono',
            field=models.CharField(max_length=500, null=True, verbose_name='Icono'),
        ),
    ]
